name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    # Removed paths-ignore: [.github/**] as it's generally good practice
    # to run CI on workflow file changes to ensure they are valid.
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: choice # Changed from 'environment' to 'choice' for direct input options
        options:
          - dev
          - staging
          - prod
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Output event and branch info
        run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          # Using github.ref_name for just the branch name, and fixed the typo for repository.
          echo "🔎 The name of your branch is ${{ github.ref_name }} and your repository is ${{ github.repository }}."

      - name: Checkout code
        # Updated to the latest recommended stable version of checkout action.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history is fetched for accurate branch name if needed

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          # 'tree' command is not always available by default. 'ls -al' is more universal.
          ls -al

  Test:
    runs-on: ubuntu-latest
    # Removed 'if: github.event_name == 'workflow_dispatch''
    # This job will now run on 'push', 'pull_request', 'schedule', and 'workflow_dispatch' events.
    needs: Build
    environment: Test
    steps:
      - name: Run Tests
        run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    # Removed 'if: github.event_name == 'workflow_dispatch''
    # This job will now run on 'push', 'pull_request', 'schedule', and 'workflow_dispatch' events.
    needs: Build
    environment: Load-Test
    steps:
      - name: Run Load Tests
        run: |
          echo "🧪 Running Load Tests..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    # Corrected the 'if' condition to match the 'prod' option from the workflow_dispatch input.
    # Added explicit check for workflow_dispatch for clarity, as production deployments
    # are often manually triggered.
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod' }}
    steps:
      - name: Checkout code for deployment
        uses: actions/checkout@v4
      - name: Deploy Step 1
        run: echo "🚀 Step 1 deploying..." && sleep 10
      - name: Deploy Step 2
        run: echo "🚀 Step 2 deploying..." && sleep 10
      - name: Deploy Step 3
        run: echo "🚀 Step 3 deploying..." && sleep 10
      - name: Deploy Step 4
        run: echo "🚀 Step 4 deploying..." && sleep 10
      - name: Deploy Step 5
        run: echo "🚀 Step 5 deploying..." && sleep 10
      - name: Deployment Complete
        run: echo "Production deployment finished!"
