name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Output event name
        run: echo "run always"
      - name: Output branch name
        run: echo "run always"
      - name: List files
        run: ls -al
