name: GitHub Actions Demo

# Trigger the workflow on manual dispatch (workflow_dispatch)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: choice
        options:
          - dev
          - staging
          - prod
